import { Knex } from "knex";
import { hashPassword } from "../src/v1/auths/utils";
import { USER_TABLE_NAME } from "../src/v1/cores/constants/table-name.constant";

interface SeedUser {
  id: number;
  fullname: string;
  email: string;
  username: string;
  role_id: number;
  phone_number: string;
  address: string;
  class_id?: number | null;
  major_id?: number | null;
}

export const USERS_DEFAULT: SeedUser[] = [
  {
    id: 1,
    fullname: "Admin Hệ Thống",
    email: "admin@quannhu.vn",
    username: "admin",
    role_id: 1,
    phone_number: "0901000001",
    address: "Ban Quản trị hệ thống, Tổng cục Hậu cần",
  },
  {
    id: 2,
    fullname: "Nguyễn Văn Kho",
    email: "canbokho1@quannhu.vn",
    username: "canbokho1",
    role_id: 2,
    phone_number: "0901000002",
    address: "Kho Quân nhu Trung ương, Hà Nội",
  },
  {
    id: 3,
    fullname: "Trần Thị Kho",
    email: "canbokho2@quannhu.vn",
    username: "canbokho2",
    role_id: 2,
    phone_number: "0901000003",
    address: "Kho Quân nhu Tổng cục Hậu cần, Hà Nội",
  },
  {
    id: 4,
    fullname: "Chỉ Huy Trưởng K48",
    email: "chihuyk48@quannhu.vn",
    username: "chihuyk48",
    role_id: 3,
    phone_number: "0901000004",
    address: "Hệ Trinh sát K48, Học viện Khoa học Quân sự",
    class_id: null,
    major_id: 1,
  },
  {
    id: 5,
    fullname: "Phạm Minh Tuấn",
    email: "phamminhtuan@quannhu.vn",
    username: "pm_tuan",
    role_id: 2,
    phone_number: "0901000005",
    address: "Kho Quân nhu Khu vực Miền Bắc",
  },
  {
    id: 6,
    fullname: "Lê Đức Mạnh",
    email: "leducmanh@quannhu.vn",
    username: "ld_manh",
    role_id: 2,
    phone_number: "0901000006",
    address: "Kho Quân nhu Khu vực Miền Trung",
  },
  {
    id: 7,
    fullname: "Vũ Hoàng Anh",
    email: "vuhoanganh@quannhu.vn",
    username: "vh_anh",
    role_id: 2,
    phone_number: "0901000007",
    address: "Kho Quân nhu Khu vực Miền Nam",
  },
  {
    id: 8,
    fullname: "Đỗ Quốc Huy",
    email: "doquochuy@quannhu.vn",
    username: "dq_huy",
    role_id: 2,
    phone_number: "0901000008",
    address: "Kho Quân nhu Cục Kỹ thuật",
  },
  {
    id: 9,
    fullname: "Bùi Thanh Sơn",
    email: "buithanhson@quannhu.vn",
    username: "bt_son",
    role_id: 2,
    phone_number: "0901000009",
    address: "Kho Quân nhu Học viện Quốc phòng",
  },
  {
    id: 10,
    fullname: "Ngô Thị Thu Hà",
    email: "ngothithuha@quannhu.vn",
    username: "nt_thuha",
    role_id: 2,
    phone_number: "0901000010",
    address: "Kho Quân nhu Sư đoàn 312",
  },
  {
    id: 11,
    fullname: "Cao Văn Bình",
    email: "caovanbinh@quannhu.vn",
    username: "cv_binh",
    role_id: 2,
    phone_number: "0901000011",
    address: "Kho Quân nhu Sư đoàn 5",
  },
  {
    id: 12,
    fullname: "Đặng Hữu Long",
    email: "danghuulong@quannhu.vn",
    username: "dh_long",
    role_id: 2,
    phone_number: "0901000012",
    address: "Kho Quân nhu Dự trữ Chiến lược",
  },
  {
    id: 13,
    fullname: "Hoàng Minh Quân",
    email: "hoangminhquan@quannhu.vn",
    username: "hm_quan",
    role_id: 2,
    phone_number: "0901000013",
    address: "Phòng kế hoạch vật tư, Hà Nội",
  },
  {
    id: 14,
    fullname: "Tạ Văn Dũng",
    email: "tavandung@quannhu.vn",
    username: "tv_dung",
    role_id: 2,
    phone_number: "0901000014",
    address: "Ban tiếp nhận vật tư, Miền Bắc",
  },
  {
    id: 15,
    fullname: "Mai Thị Hương",
    email: "maithihuong@quannhu.vn",
    username: "mt_huong",
    role_id: 2,
    phone_number: "0901000015",
    address: "Ban kiểm kê kho, Miền Trung",
  },
  {
    id: 16,
    fullname: "Lương Đức Phúc",
    email: "luongducphuc@quannhu.vn",
    username: "ld_phuc",
    role_id: 2,
    phone_number: "0901000016",
    address: "Ban bảo quản trang bị, Miền Nam",
  },
  {
    id: 17,
    fullname: "Trịnh Hải Nam",
    email: "trinhhainam@quannhu.vn",
    username: "th_nam",
    role_id: 2,
    phone_number: "0901000017",
    address: "Tổ điều phối vận chuyển, Tổng cục Hậu cần",
  },
  {
    id: 18,
    fullname: "Nguyễn Đức Thắng",
    email: "nguyenducthang@quannhu.vn",
    username: "nd_thang",
    role_id: 3,
    phone_number: "0901000018",
    address: "Hệ Trinh sát K49, Học viện Khoa học Quân sự",
    class_id: null,
    major_id: 1,
  },
  {
    id: 19,
    fullname: "Trần Quốc Việt",
    email: "tranquocviet@quannhu.vn",
    username: "tq_viet",
    role_id: 3,
    phone_number: "0901000019",
    address: "Hệ Hậu cần K48, Học viện Khoa học Quân sự",
    class_id: null,
    major_id: 2,
  },
  {
    id: 20,
    fullname: "Lê Anh Duy",
    email: "leanhduy@quannhu.vn",
    username: "la_duy",
    role_id: 3,
    phone_number: "0901000020",
    address: "Hệ Hậu cần K49, Học viện Khoa học Quân sự",
    class_id: null,
    major_id: 2,
  },
  {
    id: 21,
    fullname: "Phan Xuân Trường",
    email: "phanxuantruong@quannhu.vn",
    username: "px_truong",
    role_id: 3,
    phone_number: "0901000021",
    address: "Hệ 1 K48, Học viện Khoa học Quân sự",
    class_id: null,
    major_id: 3,
  },
  {
    id: 22,
    fullname: "Võ Minh Khôi",
    email: "vominhkhoi@quannhu.vn",
    username: "vm_khoi",
    role_id: 3,
    phone_number: "0901000022",
    address: "Hệ 2 K48, Học viện Khoa học Quân sự",
    class_id: null,
    major_id: 4,
  },
  {
    id: 23,
    fullname: "Đinh Văn Lộc",
    email: "dinhvanloc@quannhu.vn",
    username: "dv_loc",
    role_id: 3,
    phone_number: "0901000023",
    address: "Hệ 5, Đại đội 1",
    class_id: null,
    major_id: 7,
  },
  {
    id: 24,
    fullname: "Hà Quang Minh",
    email: "haquangminh@quannhu.vn",
    username: "hq_minh",
    role_id: 3,
    phone_number: "0901000024",
    address: "Hệ 5, Lớp Tham mưu",
    class_id: null,
    major_id: 7,
  },
  {
    id: 25,
    fullname: "Kiều Anh Tuấn",
    email: "kieuanhtuan@quannhu.vn",
    username: "ka_tuan",
    role_id: 3,
    phone_number: "0901000025",
    address: "Hệ 5, Lớp Bảo đảm",
    class_id: null,
    major_id: 7,
  },
  {
    id: 26,
    fullname: "Chu Văn Thành",
    email: "chuvanthanh@quannhu.vn",
    username: "cv_thanh",
    role_id: 3,
    phone_number: "0901000026",
    address: "Hệ Pháo binh K48",
    class_id: null,
    major_id: 11,
  },
  {
    id: 27,
    fullname: "Đào Ngọc Hân",
    email: "daongochan@quannhu.vn",
    username: "dn_han",
    role_id: 3,
    phone_number: "0901000027",
    address: "Hệ Bộ binh K48",
    class_id: null,
    major_id: 12,
  },
  {
    id: 28,
    fullname: "Tô Thanh Tùng",
    email: "tothanhtung@quannhu.vn",
    username: "tt_tung",
    role_id: 3,
    phone_number: "0901000028",
    address: "Hệ 5, Ban huấn luyện",
    class_id: null,
    major_id: 7,
  },
  {
    id: 29,
    fullname: "Lưu Đức Toàn",
    email: "luuductoan@quannhu.vn",
    username: "ld_toan",
    role_id: 3,
    phone_number: "0901000029",
    address: "Hệ Pháo binh, Ban huấn luyện",
    class_id: null,
    major_id: 11,
  },
  {
    id: 30,
    fullname: "Châu Minh Khang",
    email: "chauminhkhang@quannhu.vn",
    username: "cm_khang",
    role_id: 3,
    phone_number: "0901000030",
    address: "Hệ Bộ binh, Ban huấn luyện",
    class_id: null,
    major_id: 12,
  },
];

export async function seed(knex: Knex): Promise<void> {
  await knex.raw("SET FOREIGN_KEY_CHECKS = 0");
  await knex(USER_TABLE_NAME).del();

  const DEFAULT_PASSWORD = "12345678";
  const DEFAULT_PASSWORD_HASH = await hashPassword(DEFAULT_PASSWORD);

  await knex(USER_TABLE_NAME).insert(
    USERS_DEFAULT.map((user) => ({
      ...user,
      password: DEFAULT_PASSWORD_HASH,
      class_id: user.class_id ?? null,
      major_id: user.role_id === 3 ? user.major_id ?? null : null,
    })),
  );

  await knex.raw("SET FOREIGN_KEY_CHECKS = 1");
}
