const DEFAULT_PORT = 5000;
const JWT_SECURE_KEY = process.env.JWT_SECURE_KEY || "";
const MAX_FAILED_LOGIN_ATTEMPTS = Number(process.env.MAX_FAILED_LOGIN_ATTEMPTS || 3);
const TIME_LOCK_FAILED = Number(process.env.TIME_LOCK_FAILED || 900000); //15p
const RESET_PASSWORD_USER_DEFAULT = process.env.RESET_PASSWORD_USER_DEFAULT || "ResetPass@2024"
const NODE_MAILER_EMAIL = process.env.NODE_MAILER_EMAIL || "";
const NODE_MAILER_PASSWORD = process.env.NODE_MAILER_PASSWORD || "";
export {
    DEFAULT_PORT,
    JWT_SECURE_KEY,
    MAX_FAILED_LOGIN_ATTEMPTS,
    TIME_LOCK_FAILED,
    RESET_PASSWORD_USER_DEFAULT,
    NODE_MAILER_EMAIL,
    NODE_MAILER_PASSWORD
}