export const ModalEnum = {
  CLOSE_MODAL: 0,
  CREATE_USER_MODAL: 1,
  EDIT_USER_MODAL: 2,
  DELETE_USER_MODAL: 3,
  PROFILE_MODAL:4,
  CHANGE_PASSWORD:5,

  // assets
  CREATE_ASSET_MODAL:6,
  UPDATE_ASSET_MODAL:7,

  // import , export
  IMPORT_MANUAL :8,
  IMPORT_EXCEL:9,
  EXPORT_MANUAL:10,
  EXPORT_EXCEL:11,
  ASSET_TRANSACTION_DETAIL:12,
  ALLOCATIONS_ASSETS_MODAL:13,
  RETURNS_ASSETS_MODAL:14,
  DISPOSAL_ASSETS_MODAL:15,
  ALLOCATIONS_ASSETS_DETAIL_MODAL:16,
  DISPOSAL_ASSETS_DETAIL_MODAL:17,
  

  // category
  CREATE_CATEGORY_MODAL:18,
  UPDATE_CATEGORY_MODAL:19,

  // maintenance
  CREATE_MAINTENANCE_MODAL:20,

  // batches
  ASSET_DETAIL_BATCHES:21,
  TRANSACTION_DETAIL_MODAL:22,
  MAINTENANCE_UPDATE_MODAL:23,
  ASSET_IN_WH_DETAIL:24,
  EXPORT_HISTORY_MODAL:25,

  LOG_EDIT_CHANGES_MODAL:26,
  CREATE_WAREHOUSE_MODAL:27,
} as const;

export type ModalEnumType = 
  (typeof ModalEnum)[keyof typeof ModalEnum];